"$schema" = "https://schema.tauri.app/config/2"
productName = "pytauri-next-starter"
version = "0.1.0"
identifier = "com.pytauri-next-starter.app"

[build]
frontendDist = "./out"

[app]
withGlobalTauri = true

[[app.windows]]
title = "pytauri-next-starter"
width = 1280
height = 720

minWidth = 1280
minHeight = 720
maximized = true